server:
  port: 8099

spring:
  profiles:
    active: dev
  datasource:
    name: default
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://dev.mysql.apitops.com:4308/tops_payment?useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: payment_dev
    password: AZ6tksKG7kr9vaNEqGMBbnmXx4NLCf
    initialize: false
    tomcat:
      validationQuery: 'select 2'
      testOnBorrow: true
      testOnReturn: true
      testWhileIdle: true
      maxWait: 15000
      init-s-q-l: 'set names utf8mb4;'
      maxActive: 5
      maxIdle: 5
      minIdle: 5
      initialSize: 5

mybatis.config-location: classpath:mybatis-config.xml

myTestConfiguration:
  propertyA: 123
  propertyB: niubi